routes/web.php
    Route::post('modelCheck', 'ModelcheckController@modelCheck');

    # Dashboard / Index
    Route::get('/', 'JoshController@showHome')->name('dashboard');
    # crop demo
    Route::post('crop_demo', 'JoshController@cropDemo')->name('crop_demo');
    //Log viewer routes
    Route::get('log_viewers', 'Admin\LogViewerController@index')->name('log-viewers');
    Route::get('log_viewers/logs', 'Admin\LogViewerController@listLogs')->name('log_viewers.logs');
    Route::delete('log_viewers/logs/delete', 'Admin\LogViewerController@delete')->name('log_viewers.logs.delete');
    Route::get('log_viewers/logs/{date}', 'Admin\LogViewerController@show')->name('log_viewers.logs.show');
    Route::get('log_viewers/logs/{date}/download', 'Admin\LogViewerController@download')->name('log_viewers.logs.download');
    Route::get('log_viewers/logs/{date}/{level}', 'Admin\LogViewerController@showByLevel')->name('log_viewers.logs.filter');
    Route::get('log_viewers/logs/{date}/{level}/search', 'Admin\LogViewerController@search')->name('log_viewers.logs.search');
    Route::get('log_viewers/logcheck', 'Admin\LogViewerController@logCheck')->name('log-viewers.logcheck');
    //end Log viewer
    # Activity log
    Route::get('activity_log/data', 'JoshController@activityLogData')->name('activity_log.data');
//    Route::get('/', 'JoshController@index')->name('index');
});

Route::group(['prefix' => 'admin','namespace'=>'Admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {

    # User Management
    Route::group([ 'prefix' => 'users'], function () {
        Route::get('data', 'UsersController@data')->name('users.data');
        Route::get('{user}/delete', 'UsersController@destroy')->name('users.delete');
        Route::get('{user}/confirm-delete', 'UsersController@getModalDelete')->name('users.confirm-delete');
        Route::get('{user}/restore', 'UsersController@getRestore')->name('restore.user');
//        Route::post('{user}/passwordreset', 'UsersController@passwordreset')->name('passwordreset');
        Route::post('passwordreset', 'UsersController@passwordreset')->name('passwordreset');
    });
    Route::resource('users', 'UsersController');
/************ bulk import ****************************/
    Route::get('bulk_import_users', 'UsersController@import');
    Route::post('bulk_import_users', 'UsersController@importInsert');
    /****************bulk download **************************/
    Route::get('download_users/{type}', 'UsersController@downloadExcel');





    Route::get('deleted_users',['before' => 'Sentinel', 'uses' => 'UsersController@getDeletedUsers'])->name('deleted_users');

    // Email System
    Route::group(['prefix' => 'emails'], function () {
        Route::get('compose', 'EmailController@create');
        Route::post('compose', 'EmailController@store');
        Route::get('inbox', 'EmailController@inbox');
        Route::get('sent', 'EmailController@sent');
        Route::get('{email}', ['as' => 'emails.show', 'uses' => 'EmailController@show']);
        Route::get('{email}/reply', ['as' => 'emails.reply', 'uses' => 'EmailController@reply']);
        Route::get('{email}/forward', ['as' => 'emails.forward', 'uses' => 'EmailController@forward']);
    });
    Route::resource('emails', 'EmailController');

    # Group Management
    Route::group(['prefix' => 'roles'], function () {
        Route::get('{group}/delete', 'RolesController@destroy')->name('roles.delete');
        Route::get('{group}/confirm-delete', 'RolesController@getModalDelete')->name('roles.confirm-delete');
        Route::get('{group}/restore', 'RolesController@getRestore')->name('roles.restore');
    });
    Route::resource('roles', 'RolesController');

    /*routes for blog*/
    Route::group(['prefix' => 'blog'], function () {
        Route::get('{blog}/delete', 'BlogController@destroy')->name('blog.delete');
        Route::get('{blog}/confirm-delete', 'BlogController@getModalDelete')->name('blog.confirm-delete');
        Route::get('{blog}/restore', 'BlogController@restore')->name('blog.restore');
        Route::post('{blog}/storecomment', 'BlogController@storeComment')->name('storeComment');
    });
    Route::resource('blog', 'BlogController');

    /*routes for blog category*/
    Route::group(['prefix' => 'blogcategory'], function () {
        Route::get('{blogCategory}/delete', 'BlogCategoryController@destroy')->name('blogcategory.delete');
        Route::get('{blogCategory}/confirm-delete', 'BlogCategoryController@getModalDelete')->name('blogcategory.confirm-delete');
        Route::get('{blogCategory}/restore', 'BlogCategoryController@getRestore')->name('blogcategory.restore');
    });
    Route::resource('blogcategory', 'BlogCategoryController');
    /*routes for file*/
    Route::group(['prefix' => 'file'], function () {
        Route::post('create', 'FileController@store')->name('store');
        Route::post('createmulti', 'FileController@postFilesCreate')->name('postFilesCreate');
//        Route::delete('delete', 'FileController@delete')->name('delete');
        Route::get('{id}/delete', 'FileController@destroy')->name('file.delete');
        Route::get('data', 'FileController@data')->name('file.data');
        Route::get('{user}/delete', 'FileController@destroy')->name('users.delete');
    });

    /*routes for News*/
    Route::group(['prefix' => 'news'], function () {
        Route::get('data', 'NewsController@data')->name('news.data');
        Route::get('{news}/delete', 'NewsController@destroy')->name('news.delete');
        Route::get('{news}/confirm-delete', 'NewsController@getModalDelete')->name('news.confirm-delete');
    });
    Route::resource('news', 'NewsController');

    Route::get('crop_demo', function () {
        return redirect('admin/imagecropping');
    });


    /* laravel example routes */
    #Charts
    Route::get('laravel_chart', 'ChartsController@index')->name('laravel_chart');
    Route::get('database_chart', 'ChartsController@databaseCharts')->name('database_chart');

    # datatables
    Route::get('datatables', 'DataTablesController@index')->name('index');
    Route::get('datatables/data', 'DataTablesController@data')->name('datatables.data');

    # datatables
    Route::get('jtable/index', 'JtableController@index')->name('index');
    Route::post('jtable/store', 'JtableController@store')->name('store');
    Route::post('jtable/update', 'JtableController@update')->name('update');
    Route::post('jtable/delete', 'JtableController@destroy')->name('delete');



    # SelectFilter
    Route::get('selectfilter', 'SelectFilterController@index')->name('selectfilter');
    Route::get('selectfilter/find', 'SelectFilterController@filter')->name('selectfilter.find');
    Route::post('selectfilter/store', 'SelectFilterController@store')->name('selectfilter.store');

    # editable datatables
    Route::get('editable_datatables', 'EditableDataTablesController@index')->name('index');
    Route::get('editable_datatables/data', 'EditableDataTablesController@data')->name('editable_datatables.data');
    Route::post('editable_datatables/create', 'EditableDataTablesController@store')->name('store');
    Route::post('editable_datatables/{id}/update', 'EditableDataTablesController@update')->name('update');
    Route::get('editable_datatables/{id}/delete', 'EditableDataTablesController@destroy')->name('editable_datatables.delete');

//    # custom datatables
    Route::get('custom_datatables', 'CustomDataTablesController@index')->name('index');
    Route::get('custom_datatables/sliderData', 'CustomDataTablesController@sliderData')->name('custom_datatables.sliderData');
    Route::get('custom_datatables/radioData', 'CustomDataTablesController@radioData')->name('custom_datatables.radioData');
    Route::get('custom_datatables/selectData', 'CustomDataTablesController@selectData')->name('custom_datatables.selectData');
    Route::get('custom_datatables/buttonData', 'CustomDataTablesController@buttonData')->name('custom_datatables.buttonData');
    Route::get('custom_datatables/totalData', 'CustomDataTablesController@totalData')->name('custom_datatables.totalData');

    //tasks section
    Route::post('task/create', 'TaskController@store')->name('store');
    Route::get('task/data', 'TaskController@data')->name('data');
    Route::post('task/{task}/edit', 'TaskController@update')->name('update');
    Route::post('task/{task}/delete', 'TaskController@delete')->name('delete');
});



# Remaining pages will be called from below controller method
# in real world scenario, you may be required to define all routes manually

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('{name?}', 'JoshController@showView');
});

#FrontEndController
Route::get('login', 'FrontEndController@getLogin')->name('login');
Route::post('login', 'FrontEndController@postLogin')->name('login');
Route::get('register', 'FrontEndController@getRegister')->name('register');
Route::post('register','FrontEndController@postRegister')->name('register');
Route::get('activate/{userId}/{activationCode}','FrontEndController@getActivate')->name('activate');
Route::get('forgot-password','FrontEndController@getForgotPassword')->name('forgot-password');
Route::post('forgot-password', 'FrontEndController@postForgotPassword');

#Social Logins
Route::get('facebook', 'Admin\FacebookAuthController@redirectToProvider');
Route::get('facebook/callback', 'Admin\FacebookAuthController@handleProviderCallback');

Route::get('linkedin', 'Admin\LinkedinAuthController@redirectToProvider');
Route::get('linkedin/callback', 'Admin\LinkedinAuthController@handleProviderCallback');

Route::get('google', 'Admin\GoogleAuthController@redirectToProvider');
Route::get('google/callback', 'Admin\GoogleAuthController@handleProviderCallback');


# Forgot Password Confirmation
Route::post('forgot-password/{userId}/{passwordResetCode}', 'FrontEndController@postForgotPasswordConfirm');

app/Http/Controllers/Admin/RolesController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\JoshController;
use App\Http\Requests\RoleRequest;
use Redirect;
use Sentinel;
use View;

class RolesController extends JoshController
{
    /**
     * Show a list of all the roles.
     *
     * @return View
     */
    public function index()
    {
        // Grab all the roles
        $roles = Sentinel::getRoleRepository()->all();

        // Show the page
        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Role create.
     *
     * @return View
     */
    public function create()
    {
        // Show the page
        return view('admin.roles.create');
    }

    /**
     * Role create form processing.
     *
     * @param RoleRequest $request
     * @return void
     */
    public function store(RoleRequest $request)
    {
        if ($role = Sentinel::getRoleRepository()->createModel()->create(
            [
            'name' => $request->get('name'),
            'slug' => str_slug($request->get('name'))
            ]
        )
        ) {
            // Redirect to the new role page
            return Redirect::route('admin.roles.index')->with('success', trans('roles/message.success.create'));
        }

        // Redirect to the role create page
        return Redirect::route('admin.roles.create')->withInput()->with('error', trans('roles/message.error.create'));
    }


    /**
     * Role update.
     *
     * @param int $role
     * @return View
     */
    public function edit($role)
    {
        try {
            // Get the role information
            $role = Sentinel::findRoleById($role);
        } catch (RoleNotFoundException $e) {
            // Redirect to the roles management page
            return Redirect::route('admin.roles')->with('error', trans('roles/message.role_not_found', compact('id')));
        }

        // Show the page
        return view('admin.roles.edit', compact('role'));
    }

    /**
     * Role update form processing page.
     *
     * @param int
     * @param RoleRequest $request
     * @return Redirect
     */
    public function update($role, RoleRequest $request)
    {
        $role = Sentinel::findRoleById($role);

        // Update the role data
        $role->name = $request->get('name');

        // Was the role updated?
        if ($role->save()) {
            // Redirect to the role page
            return Redirect::route('admin.roles.index')->with('success', trans('roles/message.success.update'));
        } else {
            // Redirect to the role page
            return Redirect::route('admin.roles.edit', $role)->with('error', trans('roles/message.error.update'));
        }
    }

    /**
     * Delete confirmation for the given role.
     *
     * @param int $id
     * @return View
     */
    public function getModalDelete($id = null)
    {
        $model = 'roles';
        $confirm_route = $error = null;
        try {
            // Get role information
            $role = Sentinel::findRoleById($id);
            $confirm_route = route('admin.roles.delete', ['id' => $role->id]);
            return view('admin.layouts.modal_confirmation', compact('error', 'model', 'confirm_route'));
        } catch (RoleNotFoundException $e) {
            $error = trans('admin/roles/message.role_not_found', compact('id'));
            return view('admin.layouts.modal_confirmation', compact('error', 'model', 'confirm_route'));
        }
    }

    /**
     * Delete the given role.
     *
     * @param int $id
     * @return Redirect
     */
    public function destroy($id)
    {
        try {
            // Get role information
            $role = Sentinel::findRoleById($id);

            // Delete the role
            $role->delete();

            // Redirect to the role management page
            return Redirect::route('admin.roles.index')->with('success', trans('roles/message.success.delete'));
        } catch (RoleNotFoundException $e) {
            // Redirect to the role management page
            return Redirect::route('admin.roles.index')->with('error', trans('roles/message.role_not_found', compact('id')));
        }
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin/layouts/default')

{{-- Web site Title --}}
@section('title')
    @lang('admin/roles/title.create')
    @parent
@stop

{{-- Content --}}
@section('content')
<section class="content-header">
    <h1>
        @lang('roles/title.create')
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}">
                <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                @lang('general.dashboard')
            </a>
        </li>
        <li>@lang('roles/title.roles')</li>
        <li class="active">
            @lang('roles/title.create')
        </li>
    </ol>
</section>

<!-- Main content -->
<section class="content pr-3 pl-3">
    <div class="row">
        <div class="col-lg-12">
            <div class="card ">
                <div class="card-header bg-primary text-white">
                    <span> <i class="livicon" data-name="users-add" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                        @lang('roles/title.create')
                    </span>
                </div>
                <div class="card-body">
                    {!! $errors->first('slug', '<span class="help-block">Another role with same slug exists, please choose another name</span> ') !!}
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form class="form-horizontal" role="form" method="post" action="{{ route('admin.roles.store') }}">
                        <!-- CSRF Token -->

                        {{ csrf_field() }}

                        <div class="form-group {{ $errors->
                            first('name', 'has-error') }}">
                            <label for="title" class="col-sm-2 control-label">
                                @lang('roles/form.name')
                            </label>
                            <div class="col-sm-5">
                                <input type="text" id="name" name="name" class="form-control" placeholder="Role Name"
                                       value="{!! old('name') !!}">
                            </div>
                            <div class="col-sm-4">
                                {!! $errors->first('name', '<span class="help-block">:message</span> ') !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-4">
                                <a class="btn btn-danger" href="{{ route('admin.roles.index') }}">
                                    @lang('button.cancel')
                                </a>
                                <button type="submit" class="btn btn-success">
                                    @lang('button.save')
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- row-->
</section>
@stop

resources/views/admin/roles/edit.blade.php
@extends('admin/layouts/default')

{{-- Web site Title --}}
@section('title')
    @lang('roles/title.edit')
    @parent
@stop

{{-- Content --}}
@section('content')
    <section class="content-header">
        <h1>
            @lang('roles/title.edit')
        </h1>
        <ol class="breadcrumb">
            <li>
                <a href="{{ route('admin.dashboard') }}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    @lang('general.dashboard')
                </a>
            </li>
            <li>@lang('roles/title.roles')</li>
            <li class="active">@lang('roles/title.edit')</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content pl-3 pr-3">
        <div class="row">
            <div class="col-lg-12">
                <div class="card ">
                    <div class="card-header bg-primary text-white">
                        <h4 class="card-title"><i class="livicon" data-name="wrench" data-size="16" data-loop="true"
                                                  data-c="#fff" data-hc="white"></i>
                            @lang('roles/title.edit')
                        </h4>
                    </div>
                    <div class="card-body">
                    @if($role)
                        {!! Form::model($role, ['url' => URL::to('admin/roles/'. $role->id), 'method' => 'put', 'class' => 'form-horizontal']) !!}
                        <!-- CSRF Token -->
                            {{ csrf_field() }}
                            <div class="form-group {{ $errors->first('name', 'has-error') }}">
                                <div class="row">
                                    <label for="title" class="col-sm-2 control-label">
                                        @lang('roles/form.name')
                                    </label>
                                    <div class="col-sm-5">
                                        <input type="text" id="name" name="name" class="form-control"
                                               placeholder=@lang('roles/form.name') value="{!! old('name', $role->
                                    name) !!}">
                                    </div>
                                    <div class="col-sm-4">
                                        {!! $errors->first('name', '<span class="help-block">:message</span>') !!}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <label for="slug" class="col-sm-2 control-label">@lang('roles/form.slug')</label>
                                    <div class="col-sm-5">
                                        <input type="text" class="form-control" value="{!! $role->slug !!}" readonly/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="offset-sm-2 col-sm-4">
                                        <a class="btn btn-danger" href="{{ route('admin.roles.index') }}">
                                            @lang('button.cancel')
                                        </a>
                                        <button type="submit" class="btn btn-success">
                                            @lang('button.save')
                                        </button>
                                    </div>
                                </div>
                            </div>
                            {!! Form::close() !!}
                        @else
                            <h1>@lang('roles/message.error.no_role_exists')</h1>
                            <a class="btn btn-danger" href="{{ route('admin.roles.index') }}">
                                @lang('button.back')
                            </a>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <!-- row-->
    </section>

@stop

resources/views/admin/roles/index.blade.php
@extends('admin/layouts/default')

{{-- Web site Title --}}
@section('title')
    @lang('roles/title.management')
    @parent
@stop

{{-- Content --}}
@section('content')
    <section class="content-header">
        <h1>@lang('roles/title.management')</h1>
        <ol class="breadcrumb">
            <li>
                <a href="{{ route('admin.dashboard') }}">
                    <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                    @lang('general.dashboard')
                </a>
            </li>
            <li><a href="#"> @lang('roles/title.roles')</a></li>
            <li class="active">@lang('roles/title.roles_list')</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content pr-3 pl-3">
        <div class="row">
            <div class="col-lg-12">
                <div class="card ">
                    <div class="card-header bg-primary text-white clearfix">
                        <span class=" float-left"><i class="livicon" data-name="users" data-size="16"
                                                             data-loop="true" data-c="#fff" data-hc="white"></i>
                            @lang('roles')
                        </span>
                        <div class="float-right">
                            <a href="{{ route('admin.roles.create') }}" class="btn btn-sm btn-light"><span
                                        class="fa fa-plus"></span> @lang('button.create')</a>
                        </div>
                    </div>
                    <br/>
                    <div class="card-body">
                        @if ($roles->count() >= 1)
                            <div class="table-responsive-lg table-responsive-md table-responsive-sm table-responsive ">

                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>@lang('roles/table.id')</th>
                                        <th>@lang('roles/table.name')</th>
                                        <th>@lang('roles/table.users')</th>
                                        <th>@lang('roles/table.created_at')</th>
                                        <th>@lang('roles/table.actions')</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach ($roles as $role)
                                        <tr>
                                            <td>{!! $role->id !!}</td>
                                            <td>{!! $role->name !!}</td>
                                            <td>{!! $role->users()->count() !!}</td>
                                            <td>{!! $role->created_at->diffForHumans() !!}</td>
                                            <td>
                                                <a href="{{ route('admin.roles.edit', $role->id) }}">
                                                    <i class="livicon" data-name="edit" data-size="18" data-loop="true"
                                                       data-c="#428BCA" data-hc="#428BCA" title="edit role"></i>
                                                </a>
                                                <!-- let's not delete 'Admin' role by accident -->
                                                @if ($role->id !== 1)
                                                    @if($role->users()->count())
                                                        <a href="#" data-toggle="modal" data-target="#users_exists"
                                                           data-name="{!! $role->name !!}" class="users_exists">
                                                            <i class="livicon" data-name="warning-alt" data-size="18"
                                                               data-loop="true" data-c="#f56954" data-hc="#f56954"
                                                               title="@lang('roles/form.users_exists')"></i>
                                                        </a>
                                                    @else
                                                        <a href="{{ route('admin.roles.confirm-delete', $role->id) }}"
                                                           data-toggle="modal" data-id="{{ $role->id }}"
                                                           data-target="#delete_confirm">
                                                            <i class="livicon" data-name="remove-alt" data-size="18"
                                                               data-loop="true" data-c="#f56954" data-hc="#f56954"
                                                               title="@lang('roles/form.delete_role')"></i>
                                                        </a>
                                                    @endif

                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        @else
                            @lang('general.noresults')
                        @endif
                    </div>
                </div>
            </div>
        </div>    <!-- row-->
    </section>




@stop

{{-- Body Bottom confirm modal --}}
@section('footer_scripts')

    <div class="modal fade" id="users_exists" tabindex="-2" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    @lang('roles/message.users_exists')
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="deleteLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="deleteLabel">Delete Role</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    Are you sure to delete this Role? This operation is irreversible.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                    <a type="button" class="btn btn-danger Remove_square">Delete</a>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
    </div>
    {{--<script>--}}
    {{--$(function () {$('body').on('hidden.bs.modal', '.modal', function () {$(this).removeData('bs.modal');});});--}}
    {{--$(document).on("click", ".users_exists", function () {--}}

    {{--var role_name = $(this).data('name');--}}
    {{--$(".modal-header h4").text( role_name+" Role" );--}}
    {{--});</script>--}}


    <script>
        var $url_path = '{!! url('/') !!}';
        $('#delete_confirm').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var $recipient = button.data('id');
            var modal = $(this)
            modal.find('.modal-footer a').prop("href", $url_path + "/admin/roles/" + $recipient + "/delete");
        })
    </script>
@stop